config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include("users.urls")),
    path('account/', include('allauth.urls')),
    path('', include('photos.urls')),
    path('', include('tmies.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

photos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "photos"

urlpatterns = [
    path("<int:year>/<uuid:pk>/photo/", views.photoHome, name="photo_home"),
    path("<int:year>/<uuid:pk>/photo/write", views.photoCreate, name="photo_create"),
    path("<int:pk>/photo/delete/", views.photoDelete, name="photo_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static

app_name = "posts"

urlpatterns = [
    path("", views.main, name="main"),
    path('create', views.createBirthdayPage, name='create_birthday_page'),
    path('<int:year>/<uuid:pk>', views.detailBirthdayPage, name="detail_birthday_page"),
    path('<int:year>/<uuid:pk>/write/', views.createMessage, name='create_message'),
    path('<int:pk>/delete/', views.deleteMessage, name='delete_message'),
    path('mypage/main',views.mainMypage, name='main_mypage'),
    path('mypage/edit', views.editMypage, name= "edit_mypage"),
]

tmies/urls.py
from django.urls import path 
from . import views

app_name = "tmies"

urlpatterns = [
    path('<int:year>/<uuid:pk>/tmi/', views.detailTmiPage, name='detail_tmi_page'),
    path('<int:year>/<uuid:pk>/tmi/write/', views.createTmiMessage, name='create_tmi_message'),
    path('<int:pk>/tmi/delete/', views.deleteTmiMessage, name='delete_tmi_message'),
    path('like_ajax/', views.like_ajax, name ='like_ajax'),
    
]

tmies/models.py
from django.db import models
from posts.models import BirthdayPage
from users.models import User

class TmiPage(models.Model):
    tmi_origin = models.OneToOneField(BirthdayPage, on_delete=models.CASCADE, primary_key=True)
    year = models.IntegerField(null=True)
    state = models.CharField(null=True, max_length=20)
    
class TmiMessage(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer", null=True)
    receiver = models.ForeignKey(TmiPage, on_delete=models.CASCADE)
    content = models.TextField()
    like = models.IntegerField(default=0)
    like_state = models.BooleanField(default=False, verbose_name="게시글좋아요")
    

tmies/forms.py
from django import forms
from .models import TmiMessage



class TmiMessageForm(forms.ModelForm):
    class Meta:
        model = TmiMessage
        fields = ('content',)

tmies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TmiPage, TmiMessage
from .forms import TmiMessageForm
from posts.models import BirthdayPage
from photos.models import PhotoPage

import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

def detailTmiPage(request,year, pk):
    tmi_page = get_object_or_404(TmiPage, year=year, pk=pk)
    tmi_messages = tmi_page.tmimessage_set.all().order_by('-id')
    
    birthday_page = get_object_or_404(BirthdayPage, pk=pk)
    name = birthday_page.owner.nickname
    
    if request.user == birthday_page.owner :
        is_owner = 1 #현재 접속자가 이 생일 페이지의 주인인지 알려주는 플래그
    else :
        is_owner = 0
    
    target_birth = get_object_or_404(BirthdayPage, year=year, pk=pk)
    target_photo = get_object_or_404(PhotoPage, year=year, pk=pk)
    target_tmi = get_object_or_404(TmiPage, year=year, pk=pk) #하단 메뉴용 타겟들
    
    context = {
        "tmi_messages": tmi_messages,
        "pk": pk,
        "name": name,
        "is_owner": is_owner,
        "year": year,
        "tmi_page": tmi_page,
        "target_birth" : target_birth,
        "target_photo" : target_photo,
        "target_tmi" : target_tmi,
    }
    
    return render(request, template_name="tmies/detail_tmi_page.html", context=context)

def createTmiMessage(request, year, pk):
    tmi_page = get_object_or_404(TmiPage, year=year, pk=pk)
    form = TmiMessageForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            tmi = form.save(commit=False)
            tmi.receiver = tmi_page
            if request.user.is_authenticated :
                tmi.writer = request.user
            tmi.save()
            return redirect(f"/{tmi_page.year}/{tmi_page.tmi_origin.uuid}/tmi")
    context = {
        'tmi_page': tmi_page,
        'form':form,
        }
    return render(request, template_name='tmies/create_tmi_message.html', context=context)

def deleteTmiMessage(reqeust, pk):
    tmi_message = TmiMessage.objects.get(pk=pk)
    tmi_page = tmi_message.receiver
    tmi_message.delete()
    return redirect(f"/{tmi_page.year}/{tmi_page.tmi_origin.uuid}/tmi")




@csrf_exempt
def like_ajax(request):
    req = json.loads(request.body)     
    tmi_message_id = req['id']

    message = TmiMessage.objects.get(id=tmi_message_id)
    
    message.like += 1

    message.save()

    return JsonResponse({'id': tmi_message_id})
    

tmies/templates/tmies/create_tmi_message.html
{% extends 'posts/base.html' %}
{% block content %}
  {% load static %}

  <head>
    <link rel="stylesheet" href="{% static 'css/create_tmi_message.css' %}"/>
  </head>

  <body>
    <div class="content">
      <form action="{% url 'tmies:create_tmi_message' tmi_page.year tmi_page.tmi_origin.pk %}" method="POST">
        {% csrf_token %}
        <form action="" method="POST">
          <input type="hidden" name="csrfmiddlewaretoken" value="TvwoESACvOpLBiYLtw7Gsc6Wl5GNiS2IEE7cyjEPptMPPUr80hvVJhc7XaUh4reX">
          {% csrf_token %}
          <p>
            <label for="id_content" class="create_tmi--text">내 친구의 TMI를 입력해주세요.</label>
            <span class="tmi__create__sub-text">최대 70자</span>
            <div class="create_tmi--example">
              ex. 김추카의 애완견 이름은 포카이다.</div>
            <textarea name="content" cols="40" rows="5" maxlength="70" required="" id="id_content"></textarea>
          </p>
          {% csrf_token %}
          <input class="create_tmi--submit" type="submit" value="TMI 남기기">
        </form>
      </div>
    </body>
  {% endblock content %}

tmies/templates/tmies/detail_tmi_page.html
{% extends 'posts/base.html' %}
{% block title %}
  tmi 쌓기
{% endblock %}
{% block content %}
  {% load static%}

  <head>
    <link rel="stylesheet" href="{% static 'css/detail_tmi_page.css' %}"/>
  </head>

  <body>
    <div class="content">
      {% if tmi_page.state == "deactivate" %}
        <script type="text/javascript">
          alert('아직 생일 페이지가 활성화되지 않았어요!')
          window.location.href = '{% url 'posts:main' %}';
        </script>
      {% elif tmi_page.state == "activate" or tmi_page.state == "archive" %}
        {% if tmi_page.state == "archive" %}
        <div class="archive">
          <p>
            {{name}}님의
            {{year}}년 내 친구의 TMI 페이지입니다.
          </p>
        </div>
        {% else %}
          <div class="tmi_icon">
            <img src="{% static 'img\icon\talking-deactivate.png' %}" alt="">
          </div>
          <div class="text">
            <h1 class="text__title">내 친구의 TMI</h1>
            <p class="text__description tmi-description">
              {{name}}님에 대해 누가누가 더 잘 아나요?</br>
              내 친구의 소소한 TMI들을 같이 공유해주세요.</br>
              <p class="text__description__sub-text">
              재밌는 내용에는 하트를 눌러보세요.
              </p>
            </p>
          </div>
        {% endif %}

        {% if not is_owner %}
          {% if not tmi_page.state == "archive" %}
            {% if request.user.is_authenticated %}
              <a href="{% url 'tmies:create_tmi_message' year pk %}" class="floating-btn">
                <p class="floating-btn__text">내 친구의 TMI 남기기</p>
              </a>
            {% else %}
              <div class="floating-btn" id="login-btn">
                <p class="floating-btn__text">내 친구의 TMI 남기기</p>
              </div>
            {% endif %}
          {% endif %}
        {% endif %}

        {% if tmi_messages %}
          <div class="messages">
            {% for tmi_message in tmi_messages%}
              <div class="message-id-{{ tmi_message.id }}">
                <div class="message_area">
                  <div class="message_content">
                    <p>
                      {{ tmi_message.content }}
                    </p>
                  </div>
                  <div class="message_side">
                    {% if not tmi_page.state == "archive"%}
                      {% if is_owner or request.user == tmi_message.writer %}
                        <span class="messaage_delete delete-btn">
                          <button id={% url 'tmies:delete_tmi_message' tmi_message.id %} class="delete-btn">
                            삭제
                          </button>
                        </span>
                      {% else %}
                        <span class="messaage_delete">
                          <p class="delete_text">&nbsp;</p>
                        </span>
                      {% endif %}
                      <div class="like_area">
                        <button class="message_like_button" onclick="onClickLike({{ tmi_message.id }})">
                          <img src="{% static 'img/icon/heart.svg' %}" alt="">
                        </button>
                        <p class="message_like">
                          {{ tmi_message.like }}
                        </p>
                      </div>
                    {% else %}
                      <span class="messaage_delete">
                        <p class="delete_text">&nbsp;</p>
                      </span>
                      <div class="like_area">
                        <button class="message_like_button" onclick="onClickLike({{ tmi_message.id }})">
                          <img src="{% static 'img/icon/heart.svg' %}" alt="">
                        </button>
                        <p class="message_like">
                          {{ tmi_message.like }}
                        </p>
                      </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        {% else %}
        <div class="tmies--empty">
          <h1>아직 남겨진 TMI가 없어요.</h1>
          <h6>이렇게 남겨보세요.</h6>
          <img src="{% static 'img\main-image-tmi-monochrome.png' %}" alt=""><br>
        </div>
        {% endif %}
      {% endif %}
    </div>
    {% if tmi_page.state == "activate" or tmi_page.state == "archive"%}
      <!-- 하단 메뉴 표시되도록 하는 부분. -->
      <div class="nav-bottom">
        <div class="nav-bottom__content">
          <a class="nav-bottom__content__birthdaypage" href="{% url 'posts:detail_birthday_page' target_birth.year target_birth.pk %}">
            <img src="{% static 'img\icon\birthday-cake-deactivate.png' %}" alt="">
            <h6>축하메세지</h6>
          </a>
          <a class="nav-bottom__content__photo" href="{% url 'photos:photo_home' target_photo.year target_photo.photo_origin.pk %}">
            <img src="{% static 'img\icon\image-deactivate.png' %}" alt="">
            <h6>포토방명록</h6>
          </a>
          <a class="nav-bottom__content__tmi" href="{% url 'tmies:detail_tmi_page' target_tmi.year target_tmi.tmi_origin.pk%}">
            <img src="{% static 'img\icon\talking-activate.png' %}" alt="">
            <h6>내 친구의 TMI</h6>
          </a>
        </div>
      </div>
    {% endif %}

    <!-- 로그인 모달-->
    <div class="modal__login hidden">
      <div class="modal__login__overlay"></div>
      <div class="modal__login__content">
        <span class="modal__login__content__title">로그인 하지 않고<br/>메시지를 남기시겠어요?</span>
        <div class="modal__login__content__description">
          <h6>로그인을 하지 않으면&nbsp</h6>
          <div class="description__line">
            <h6>내가 남긴&nbsp</h6>
            <h6>TMI를 &nbsp</h6>
          </div>
          <h6 class="bold">삭제할 수 없어요.</h6>
        </div>
        <div class="modal__login__content__btns">
          <div class="login__social_login">
            <a href="/login/?next={{ request.path }}" class="login__yes">
              <div class="login__yes__text">소셜 로그인 하러가기</div>
            </a>
            <a href="{% url 'tmies:create_tmi_message' year pk %}" class="login__no" id="login__no">
              <div class="login__no__text">로그인 없이 남기기</div>
            </a>
          </div>

        </div>
      </div>
    </div>
    <!--삭제 모달-->
    <div class="modal__delete hidden">
      <div class="modal__delete__overlay"></div>
      <div class="modal__delete__content">
        <span class="modal__delete__content__title">정말 삭제하시겠어요?</span>
        <div class="modal__delete__content__description">
          삭제한 포토 방명록은 되돌릴 수 없어요.
        </div>
        <div class="modal__delete__content__btns">
          <button class="modal__delete__cancel">취소</button>
          <a href="" class="modal__delete__confirm">삭제</a>
        </div>
      </div>
    </div>


    <script>
      //tmi 메세지 리스트 정렬용
      const colorTarget = document.getElementsByClassName("message_content")
      const fullTarget = document.getElementsByClassName("message_area")
      var colors = ['#A7DD71', '#EDADDA', '#FF8F87', '#FFDA96', '#93B8E1']

      for (i = 0; i < colorTarget.length; i++) {
        color = colors[i % 5]
        colorTarget[i].style.backgroundColor = color;
      }

      for (j = 0; j < fullTarget.length; j++) {
        if (j % 2 == 0) {
          fullTarget[j].style.marginLeft = '3.5rem';
          fullTarget[j]
            .classList
            .add("slideRight")
        } else {
          fullTarget[j].style.marginLeft = '1rem'
          fullTarget[j].style.marginRight = '3.5rem'
          fullTarget[j]
            .classList
            .add("slideLeft")
        }
      }

      //삭제 모달
      const openButton = document.getElementsByClassName("delete-btn");
      const modalDelete = document.querySelector(".modal__delete");
      const cancelButton = modalDelete.querySelector(".modal__delete__cancel");
      const deleteButton = modalDelete.querySelector(".modal__delete__confirm");

      const openModalDelete = (e) => {
        deleteButton.href = e.target.id;
        modalDelete
          .classList
          .remove("hidden");
      }
      const cancelModalDelete = () => {
        modalDelete
          .classList
          .add("hidden");
      }

      for (i = 0; i < openButton.length; i++) {
        openButton[i].addEventListener("click", openModalDelete);
      }
      cancelButton.addEventListener("click", cancelModalDelete);

      // 좋아요 ajax
      const strip = (string) => {
        return string.replace(/^\s+|\s+$/g, '');
      };

      const onClickLike = async (id) => {

        const url = "/like_ajax/"
        const res = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
          },
          body: JSON.stringify({id: id})
        });
        const {id: msgId} = await res.json();
        likeHandleResponse(msgId)
      }

      const likeHandleResponse = (id) => {
        const element = document.querySelector(`.message-id-${id} .message_like`);
        const num = element.innerHTML;
        const count = Number(num) + 1;

        element.innerHTML = `${count}`;
      }

      //로그인 모달
      const openButtonLogin = document.getElementById("login-btn");
      const modalLogin = document.querySelector(".modal__login");
      const closeButtonLogin = document.getElementById("login__no");

      const openModalLogin = () => {
        modalLogin
          .classList
          .remove("hidden");
      }
      const closeModalLogin = () => {
        modalLogin
          .classList
          .add("hidden");
      }

      openButtonLogin.addEventListener("click", openModalLogin);
      closeButtonLogin.addEventListener("click", closeModalLogin);

      const background_login = document.getElementsByClassName("modal__login__overlay")[0]
      background_login.onclick = function () {
        modalLogin
          .classList
          .add("hidden");
      }
    </script>

  </body>
{% endblock %}