config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include("users.urls")),
    path('account/', include('allauth.urls')),
    path('', include('photos.urls')),
    path('', include('tmies.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

posts/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static

app_name = "posts"

urlpatterns = [
    path("", views.main, name="main"),
    path('create', views.createBirthdayPage, name='create_birthday_page'),
    path('<int:year>/<uuid:pk>', views.detailBirthdayPage, name="detail_birthday_page"),
    path('<int:year>/<uuid:pk>/write/', views.createMessage, name='create_message'),
    path('<int:pk>/delete/', views.deleteMessage, name='delete_message'),
    path('mypage/main',views.mainMypage, name='main_mypage'),
    path('mypage/edit', views.editMypage, name= "edit_mypage"),
]

users/urls.py
# users/urls.py 
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="log_in"),
    path("logout/", views.log_out, name="log_out"),
    path("signup/", views.sign_up, name="sign_up"),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class User(AbstractUser):
    nickname = models.CharField(null=True, blank=True, max_length=50)
    email = models.EmailField(null=True, blank=True)
    birthday = models.DateField(null=True, blank=True,default=timezone.now)
    selected_cake = models.CharField(max_length=10, null=True, blank=True)

    
	

users/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django
django.setup()
from users.models import User

class LoginForm(forms.Form):
    username = forms.CharField(label='username')
    password = forms.CharField(widget=forms.PasswordInput,label='password')

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        

        try:
            user = User.objects.get(username=username)

            if user.check_password(password):
                return self.cleaned_data
            else:
                print('err')
                raise forms.ValidationError("password is wrong")

        except User.DoesNotExist:
            raise forms.ValidationError("There is no user")

class SignupForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username',  'password1', 'password2', 'birthday']
    
    def save(self, user):
        user.save()
        

users/views.py
# Create your views here.
from django.shortcuts import redirect, render
from django.views import View
from . import forms
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from posts.views import BirthdayPage

from datetime import datetime

#도메인 년도 비교용 전역변수
today = datetime.now().date() #현재 날짜
today_year = today.year #현재 년도
next_year = today_year + 1

class LoginView(View):
    forms 
    def get(self, request):
        form = forms.LoginForm()
        ctx = {"form": form}
        global redirect_to 
        redirect_to = request.GET.get('next', '')
        return render(request, "./users/login.html", ctx)
    
    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
            return HttpResponseRedirect(redirect_to)

        return render(request, "./users/login.html", {"form": form})

@login_required
def log_out(request):
    logout(request)
    return redirect("posts:main")


def sign_up(request):
    if request.method == "POST":
        form = forms.SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return render(request, "./posts/main.html")
        return redirect("users:sign_up")
    else:
        form = forms.SignupForm()
        return render(request, "./users/signup.html", {"form": form})
    
    

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css"
    />

    <script>
      $.ajaxSetup({
        headers: { "X-CSRFToken": "{{csrf_token}}" },
      });
    </script>
    <script
      src="https://kit.fontawesome.com/40607578ab.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    <nav id="nav">
      <div class="nav--right">
        {% if user.is_authenticated %}

        <a href="{% url 'users:log_out' %}">로그아웃</a>
        {% else %}
        <a href="{% url 'users:log_in' %}">로그인</a>
        <!--<a href="{% url 'users:sign_up' %}">회원가입</a>-->
        <!--<a href="{% url 'account_signup' %}" class="nav-link">Signup</a>-->
        {% endif %}
      </div>
    </nav>

    {% block content %} {% endblock content %}
  </body>
</html>

users/templates/users/login.html
{% load socialaccount %} {% block content %}
<script>
  $.ajaxSetup({
    headers: { "X-CSRFToken": "{{csrf_token}}" },
  });
</script>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- css 참조 안쓰고 그냥 style로 함. -->
    <link rel="icon" href="/static/img/page_logo/favicon.png">
    <title>추카포카</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
  </head>


  <body>
    <div class="wrap">
      <div class="screen">
        
        <div class="background">
          <div class="login--main">
            {% comment %} <span class="title">LOGIN</span>
      
            <form method="POST" action="" class="form--content">
              {% csrf_token %}
              <!-- 어떤 것을 받아올지는 view에 있는 context를 확인하면 됨(이름을 받아와야함) -->
              <div class="username"><span>Username: </span> {{form.username}}</div>
              <div class="password"><span>Password: </span> {{form.password}}</div>
              <div class="btn">
                <input type="submit" value="login" class="submit--button" />
              </div>
            </form>  {% endcomment %}
            <div class="content">
            <img class="main__logo" src="{% static 'img\page_logo\logo-main.png' %}" alt="">

            <div class="login__social_login">
              <form action="{% provider_login_url 'kakao' %}" method="post">
                {% csrf_token %}
                  <button type="submit" id="login__kakao">
                    <img src="{% static 'img/kakao-logo.png' %}">
                    <span class="kakao__text"> 카카오로 로그인</span>
                  </button>
              </form>
            <form action="{% provider_login_url 'naver' %}" method="post">
              {% csrf_token %}
              <button type="submit" id="login__naver"><img src="{% static 'img/naver-logo.png' %}"><span class="naver__text"> 네이버로 로그인</span></button>
            </form>
            
            <form action="{% provider_login_url 'google' %}" method="post">
              {% csrf_token %}
              <button type="submit" id="login__google"><img src="{% static 'img/google-logo.png' %}"><span class="google__text"> 구글로 로그인</span></button>
            </form>
          </div>
          </div>
          </div>
        </div>
      </div>
    </div>
    
  <script src="https://kit.fontawesome.com/a8a24f1fa9.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="/static/js/dropdown_menu.js"></script>
    </script>
  </body>


  
</html>
{% endblock content %}

users/templates/users/main.html
{% extends 'users/base.html' %} {% block content %}
<script>
  $.ajaxSetup({
    headers: { "X-CSRFToken": "{{csrf_token}}" },
  });
</script>
<section class="container">
  {% if user.is_authenticated %}
  <p class="main__login">{{user.username}}님이 로그인 중</p>

  {% endif %}
  <!--<a href="{% url 'account_signup' %}" class="nav-link">Signup</a>

  <a href="{% url 'account_login' %}" class="nav-link">Login</a>-->
</section>
{% endblock content %}

users/templates/users/signup.html
{% extends 'users/base.html' %} {% block content %}
<script>
  $.ajaxSetup({
    headers: { "X-CSRFToken": "{{csrf_token}}" },
  });
</script>
<div class="background">
  <div class="signup--main">
    <span class="title">Sign Up</span>
    <form method="POST" action="" class="form--content">
      {% csrf_token %}
      <div class="username">
        <span>Username: </span>
        {{form.username}}
      </div>
      <div class="password1">
        <span>Password: </span>
        {{form.password1}}
        <p class="text">
          - 알파벳/숫자 포함 최소 8자 이상의 비밀번호를 입력해주세요.
        </p>
      </div>
      <div class="password2">
        <span>Password 확인: </span>
        {{form.password2}}
        <p class="text">
          - 확인을 위해 이전과 동일한 비밀번호와 동일한 비밀번호를 입력해주세요.
        </p>
      </div>
      <div>
        <span>생일 입력(ex. 2020-01-01): </span>
        {{form.birthday}}
      </div>
      <div class="btn">
        <input type="submit" value="SignUp" class="submit--btn" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}