config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include("users.urls")),
    path('account/', include('allauth.urls')),
    path('', include('photos.urls')),
    path('', include('tmies.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

photos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "photos"

urlpatterns = [
    path("<int:year>/<uuid:pk>/photo/", views.photoHome, name="photo_home"),
    path("<int:year>/<uuid:pk>/photo/write", views.photoCreate, name="photo_create"),
    path("<int:pk>/photo/delete/", views.photoDelete, name="photo_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static

app_name = "posts"

urlpatterns = [
    path("", views.main, name="main"),
    path('create', views.createBirthdayPage, name='create_birthday_page'),
    path('<int:year>/<uuid:pk>', views.detailBirthdayPage, name="detail_birthday_page"),
    path('<int:year>/<uuid:pk>/write/', views.createMessage, name='create_message'),
    path('<int:pk>/delete/', views.deleteMessage, name='delete_message'),
    path('mypage/main',views.mainMypage, name='main_mypage'),
    path('mypage/edit', views.editMypage, name= "edit_mypage"),
]

tmies/urls.py
from django.urls import path 
from . import views

app_name = "tmies"

urlpatterns = [
    path('<int:year>/<uuid:pk>/tmi/', views.detailTmiPage, name='detail_tmi_page'),
    path('<int:year>/<uuid:pk>/tmi/write/', views.createTmiMessage, name='create_tmi_message'),
    path('<int:pk>/tmi/delete/', views.deleteTmiMessage, name='delete_tmi_message'),
    path('like_ajax/', views.like_ajax, name ='like_ajax'),
    
]

photos/models.py
from django.db import models
from posts.models import BirthdayPage
from users.models import User

class PhotoPage(models.Model):
    photo_origin = models.OneToOneField(BirthdayPage, on_delete=models.CASCADE, primary_key=True)
    year = models.IntegerField(null=True)
    state = models.CharField(null=True, max_length=20)
    

class Photo(models.Model):
    photo_uploader = models.ForeignKey(User, on_delete=models.CASCADE, related_name="photo_uploader", null=True)
    receiver = models.ForeignKey(PhotoPage, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, verbose_name="제목")
    req_photo = models.ImageField(upload_to='photos/%Y%m%d', verbose_name="사진")

photos/forms.py
from django.forms import ModelForm
from .models import Photo

class PhotoCreateForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['title', 'req_photo']

photos/views.py
from django.shortcuts import redirect, render, get_object_or_404

from .forms import PhotoCreateForm
from .models import Photo
from .models import PhotoPage
from posts.models import BirthdayPage
from tmies.models import TmiPage

def photoHome(request, year, pk):
    photo_page = get_object_or_404(PhotoPage, year=year, pk=pk)
    photos = photo_page.photo_set.all()

    bp_owner = get_object_or_404(BirthdayPage, year=year ,pk=pk)
    name = bp_owner.owner.nickname
    
    if request.user == bp_owner.owner :
        is_owner = 1 #현재 접속자가 이 생일 페이지의 주인인지 알려주는 플래그
    else :
        is_owner = 0
    
    target_birth = get_object_or_404(BirthdayPage, year=year, pk=pk)
    target_photo = get_object_or_404(PhotoPage, year=year, pk=pk)
    target_tmi = get_object_or_404(TmiPage, year=year, pk=pk) #하단 메뉴용 타겟들

    context = {
        "photos" : photos,
        "pk" : pk,
        "name": name,
        "is_owner": is_owner,
        "year": year,
        "photo_page": photo_page,
        "target_birth" : target_birth,
        "target_photo" : target_photo,
        "target_tmi" : target_tmi,
    }

    return render(request, "photos/photo_home.html", context=context)


def photoCreate(request, year, pk):
    photo_page = get_object_or_404(PhotoPage, year=year, pk=pk)
    form = PhotoCreateForm(request.POST, request.FILES)
    if request.method == "POST":

        if form.is_valid():
            photo = form.save(commit=False)
            photo.receiver = photo_page
            if request.user.is_authenticated :
                photo.photo_uploader = request.user
            photo.save()
            return redirect(f"/{photo_page.year}/{photo_page.photo_origin.uuid}/photo")
    context = {
        'photo_page' : photo_page,
        'form' : form,
    }
    return render(request, template_name='photos/photo_create.html', context=context)

def photoDelete(reqeust, pk):
    photo = Photo.objects.get(pk=pk)
    photo_page = photo.receiver
    photo.delete()
    return redirect(f"/{photo_page.year}/{photo_page.photo_origin.uuid}/photo")

photos/templates/photos/photo_create.html
<!DOCTYPE html>
{% extends 'posts/base.html' %} {% block content %}

<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/photo_create.css' %}" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>포토 업로드</title>
  </head>

  <body>
    <div class="content">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input
          type="hidden"
          name="csrfmiddlewaretoken"
          value="fEvBAjDqYTbT0g2TO8Qa36V8uOODaegknvhClSlrEcFobmhnqrFseu2keYaVllMC"
        />
        {% csrf_token %}
        <p>
          <div class="filebox">
          <span id="id_req_photo--text"
            >업로드할 사진을 골라주세요.<span>

          <div>
          <input class="upload-name" placeholder="파일을 선택해 주세요">
          <label for="id_req_photo" id="id_req_photo--button">파일 업로드</label>
          <input style="display:none;" type="file" name="req_photo" accept="image/*" required="" id="id_req_photo">
          </div>
          </div>
        </p>
        {% csrf_token %}
        <p>
          <label for="id_title" id="id_title--text" 
            >한줄 소개를 작성해 주세요.</label
          >
          <span class="photo__create__sub-text">최대 30자</span>
          <input
            type="text"
            name="title"
            maxlength="50"
            required=""
            id="id_title"
            placeholder="어떤 사진인가요?"
          />
        </p>
        
        <div>
          <input type="submit" class="photo_create--submit" value="포토 방명록 남기기" />
        </div>
      </form>
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script>
    //첨부파일 이름 변경
    $("#id_req_photo").on('change',function(){
      var fileName = $("#id_req_photo").val();
      var words = fileName.split('\\');
      $(".upload-name").val(words[2]);
    });
  </script>
</html>
{% endblock %}

photos/templates/photos/photo_home.html
{% extends 'posts/base.html' %}
{% block content %}
  {% load static%}

  <head>
    <link rel="stylesheet" href="{% static 'css/photo_home.css' %}"/>
  </head>

  <body>
    <div class="content">
    {% if photo_page.state == "deactivate" %}
        <script type="text/javascript">
          alert('아직 생일 페이지가 활성화되지 않았어요!')
          window.location.href = '{% url 'posts:main' %}';
        </script>
    {% elif photo_page.state == "activate" or photo_page.state == "archive" %}
        {% if photo_page.state == "archive" %}
          <div class="archive">
            <p>
              {{name}}님의
              {{year}}년 포토 방명록 페이지입니다.
            </p>
          </div>
          {%else%}
          <div class="photo_icon">
            <img src="{% static 'img\icon\image-deactivate.png' %}" alt="">
          </div>
          <div class="text">
            <h1 class="text__title">포토방명록</h1>
            <p class="text__description">
              {{ name }}님과의 즐거웠던 순간은 언제였나요?</br>
              추억이 담겨있는 사진들과 함께 축하를 남겨주세요!
            </p>
          </div>
        {%endif%}
        <div class="images">
          {% if photos %}
            <div class="images__container">
              {% for photo in photos %}
                <div class="images__item">
                  <div class="images__item__sticker rotate"></div>
                  <!--<img class="images__item__pin rotate" src="{% static 'img/pin.png' %}" alt="">-->
                  {% if is_owner or request.user == photo.photo_uploader %}
                    {% if not photo_page.state == "archive" %}
                      <p class="images__item__delete-btn">
                        <button id={% url 'photos:photo_delete' photo.id %} class="delete-btn">
                          삭제
                        </button>
                      </p>
                    {% endif %}
                  {% else %}
                    <p class="images__item__delete-btn">
                      &nbsp;
                    </p>
                  {% endif %}
                  <div class="images__item__polaroid">
                    <p><img class="images__item__image" src=" {{photo.req_photo.url}}" alt=""></p>
                    <h3>{{photo.title}}</h3>
                  </div>
                </div>
              {% endfor %}
            </div>
        </div>
        {% else %}
          
          <div class="images--empty">
            <h1>아직 남겨진 포토 방명록이 없어요.</h1>
            <h6>이렇게 남겨보세요.</h6>
            <img src="{% static 'img\main-image-photo-monochrome.png' %}" alt=""><br>
          </div>
        {% endif %}
    {%endif %}
    </div>
      
      {% if not is_owner %}
        {% if not photo_page.state == "archive" %}
          {% if request.user.is_authenticated %}
            <a href="{% url 'photos:photo_create' year pk %}" class="floating-btn">
              <p class="floating-btn__text">포토 방명록 남기기</p>
            </a>
          {% else %}
            <div class="floating-btn" id="login-btn">
              <p class="floating-btn__text">포토 방명록 남기기</p>
            </div>
          {% endif %}
        {% endif %}
      {% endif %}

    {% if photo_page.state == "activate" or photo_page.state == "archive"%}
      <!-- 하단 메뉴 표시되도록 하는 부분. -->
      <div class="nav-bottom">
        <div class="nav-bottom__content">
          <a class="nav-bottom__content__birthdaypage" href="{% url 'posts:detail_birthday_page' target_birth.year target_birth.pk %}">
            <img src="{% static 'img\icon\birthday-cake-deactivate.png' %}" alt="">
            <h6>축하메세지</h6>
          </a>
          <a class="nav-bottom__content__photo" href="{% url 'photos:photo_home' target_photo.year target_photo.photo_origin.pk %}">
            <img src="{% static 'img\icon\image-activate.png' %}" alt="">
            <h6>포토방명록</h6>
          </a>
          <a class="nav-bottom__content__tmi" href="{% url 'tmies:detail_tmi_page' target_tmi.year target_tmi.tmi_origin.pk%}">
            <img src="{% static 'img\icon\talking-deactivate.png' %}" alt="">
            <h6>내 친구의 TMI</h6>
          </a>
        </div>
      </div>
    {%endif %}
  
  
</body>
<!-- 이미지 크게 보기 모달 -->
<div id="modal__images">
  <span class="modal__images--close"><img src="{% static 'img/icon/close.svg' %}" alt=""></span>
  <img class="modal__images__content" id="image-original">
</div>

<!--삭제 모달-->
<div class="modal__delete hidden">
  <div class="modal__delete__overlay"></div>
  <div class="modal__delete__content">
    <span class="modal__delete__content__title">정말 삭제하시겠어요?</span>
    <div class="modal__delete__content__description">
      삭제한 포토 방명록은 되돌릴 수 없어요.
    </div>
    <div class="modal__delete__content__btns">
      <button class="modal__delete__cancel">취소</button>
      <a href="" class="modal__delete__confirm">삭제</a>
    </div>
  </div>
</div>

<!-- 로그인 모달-->
<div class="modal__login hidden">
  <div class="modal__login__overlay"></div>
  <div class="modal__login__content">
    <span class="modal__login__content__title">로그인 하지 않고<br/>메시지를 남기시겠어요?</span>
    <div class="modal__login__content__description">
      <h6>로그인을 하지 않으면&nbsp</h6> 
      <div class="description__line">
        <h6>내가 남긴&nbsp</h6>
        <h6>포토 방명록을&nbsp</h6>
      </div>
      <h6 class="bold">삭제할 수 없어요.</h6>
    </div>
    <div class="modal__login__content__btns">
      <div class="login__social_login">
        <a href="/login/?next={{ request.path }}" class="login__yes">
          <div class="login__yes__text">소셜 로그인 하러가기</div>
        </a>
        <a href="{% url 'photos:photo_create' year pk %}" class="login__no" id="login__no">
          <div class="login__no__text">로그인 없이 남기기</div>
        </a>
      </div>
    </div>
  </div>
</div>
<script>
  //나무집게 랜덤 회전
  var randomList = [
    '-10',
    '-7',
    '-5',
    '5',
    '7',
    '10'
  ]
  const getRandom = (min, max) => Math.random() * (max - min) + min;
  var rand;
  var colors = ['#A7DD71', '#EDADDA', '#FF8F87', '#FFDA96', '#93B8E1']
  var pin = document.getElementsByClassName("rotate")
  for (i = 0; i < pin.length; i++) {
    //회전
    rand = randomList[Math.floor(Math.random() * randomList.length)];
    console.log(rand)
    pin[i].style.transform = 'rotate(' + rand + 'deg)';
    //색변경
    color = colors[i % 5]
    pin[i].style.backgroundColor = color;

  }

  //사진 클릭 시 크게 보기
  var modalImages = document.getElementById("modal__images");

  // Get the image and insert it inside the modal - use its "alt" text as a caption
  var img = document.getElementsByClassName("images__item__image");
  var imgOriginal = document.getElementById("image-original");
  var nav = document.getElementsByTagName("nav")[0];
  for (i = 0; i < img.length; i++) {
    img[i].onclick = function () {
      modalImages.style.display = "block";
      imgOriginal.src = this.src;
      nav.style.display = "none"
    }
  }

  var span = document.getElementsByClassName("modal__images--close")[0];
  span.onclick = function () {
    modalImages.style.display = "none";
    nav.style.display = "flex"
  }
  var background = document.getElementById("modal__images");
  background.onclick = function () {
    modalImages.style.display = "none";
    nav.style.display = "flex"
  }

  //삭제 모달
  const openButton = document.getElementsByClassName("delete-btn");
  const modalDelete = document.querySelector(".modal__delete");
  const cancelButton = modalDelete.querySelector(".modal__delete__cancel");
  const deleteButton = modalDelete.querySelector(".modal__delete__confirm");

  const openModalDelete = (e) => {
    deleteButton.href = e.target.id;
    modalDelete
      .classList
      .remove("hidden");
  }
  const cancelModalDelete = () => {
    modalDelete
      .classList
      .add("hidden");
  }

  for (i = 0; i < openButton.length; i++) {
    openButton[i].addEventListener("click", openModalDelete);
  }
  cancelButton.addEventListener("click", cancelModalDelete);

  //로그인 모달
  const openButtonLogin = document.getElementById("login-btn");
  const modalLogin = document.querySelector(".modal__login");
  const closeButtonLogin = document.getElementById("login__no");

  const openModalLogin = () => {
    modalLogin.classList.remove("hidden");
  }
  const closeModalLogin = () => {
    modalLogin.classList.add("hidden");
  }
  
  openButtonLogin.addEventListener("click", openModalLogin);
  closeButtonLogin.addEventListener("click", closeModalLogin);

  const background_login = document.getElementsByClassName("modal__login__overlay")[0]
  background_login.onclick = function () {
    modalLogin.classList.add("hidden");
  }
</script>
{% endblock %}