config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include("users.urls")),
    path('account/', include('allauth.urls')),
    path('', include('photos.urls')),
    path('', include('tmies.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

posts/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls.static import static

app_name = "posts"

urlpatterns = [
    path("", views.main, name="main"),
    path('create', views.createBirthdayPage, name='create_birthday_page'),
    path('<int:year>/<uuid:pk>', views.detailBirthdayPage, name="detail_birthday_page"),
    path('<int:year>/<uuid:pk>/write/', views.createMessage, name='create_message'),
    path('<int:pk>/delete/', views.deleteMessage, name='delete_message'),
    path('mypage/main',views.mainMypage, name='main_mypage'),
    path('mypage/edit', views.editMypage, name= "edit_mypage"),
]

users/urls.py
# users/urls.py 
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="log_in"),
    path("logout/", views.log_out, name="log_out"),
    path("signup/", views.sign_up, name="sign_up"),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

posts/models.py
from django.db import models
from users.models import User
import uuid

class BirthdayPage(models.Model):
    uuid = models.UUIDField(default = uuid.uuid4, primary_key=True, editable=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    year = models.IntegerField(null=True)
    state = models.CharField(null=True, max_length=20)
    
    
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender", null=True)
    receiver = models.ForeignKey(BirthdayPage, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=20)
    message = models.TextField()
    is_private = models.BooleanField(default=False)
    profile_img = models.TextField()
    

posts/forms.py
from django import forms
from .models import Message
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")


import django
django.setup()
from users.models import User


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('sender', 'receiver','is_private', 'profile_img')

class LoginedMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('sender', 'receiver', 'profile_img')
        
class BirthdayPageForm(forms.ModelForm):
    CAKE_CHOICES = [
        ("choco", "초코"),
        ("strawberry", "딸기"),
        ("carrot", "당근"),
    ]
    from datetime import datetime
    
    
    selected_cake = forms.ChoiceField(choices=CAKE_CHOICES, widget=forms.RadioSelect)
    birthday = forms.DateField(
        widget=forms.widgets.DateInput(attrs={'type': 'date'})
    )
    class Meta:
        model = User
        fields = ('nickname', 'birthday', 'selected_cake')

class EditMyPageForm(forms.ModelForm):
    CAKE_CHOICES = [
        ("choco", "초코"),
        ("strawberry", "딸기"),
        ("carrot", "당근"),
    ]
    selected_cake = forms.ChoiceField(choices=CAKE_CHOICES, widget=forms.RadioSelect)
    class Meta:
        model = User
        fields = ('nickname','selected_cake')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from datetime import date, datetime, timedelta
from users.models import User
from .models import BirthdayPage
from .models import Message
from photos.models import PhotoPage
from .forms import MessageForm, LoginedMessageForm, BirthdayPageForm
from .forms import MessageForm, BirthdayPageForm, EditMyPageForm
from tmies.models import TmiPage
import random

#도메인 년도 비교용 전역변수
today = datetime.now().date() #현재 날짜
today_year = today.year #현재 년도
next_year = today_year + 1

def main(request):
    if request.user.is_authenticated: #로그인 한 사용자라면 
        #birthday page가 이미 만들어졌다면
        if BirthdayPage.objects.filter(owner=request.user, year=next_year).exists() : #birthday page가 내년 page라면 (올해 생일이 이미 지났다면)
            current_birthday_page = BirthdayPage.objects.get(owner=request.user, year=next_year)
            return redirect(f"{current_birthday_page.year}/{current_birthday_page.uuid}") #해당 페이지로 이동한다
        elif BirthdayPage.objects.filter(owner=request.user, year=today_year).exists():       #birthday page가 올해 page라면
            current_birthday_page = BirthdayPage.objects.get(owner=request.user, year=today_year)
            return redirect(f"{current_birthday_page.year}/{current_birthday_page.uuid}")
    return render(request, "posts/main.html")

def createBirthdayPage(request):
    #도메인 년도 비교용 전역변수
    today = datetime.now().date() #현재 날짜
    today_year = today.year #현재 년도
    next_year = today_year + 1
    
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = BirthdayPageForm(request.POST)
            if form.is_valid():
                #현재 로그인 한 유저를 owner로 하는 birthday page 생성
                birthday_page = BirthdayPage.objects.create(owner=request.user)
                #form에 입력한 정보대로 owner의 full name과 birthday 수정 후 저장
                birthday_page.owner.nickname = form.cleaned_data['nickname']
                birthday_page.owner.birthday = form.cleaned_data['birthday']
                birthday_page.owner.selected_cake = form.cleaned_data['selected_cake']
                birthday_page.owner.save()
                
                tmi_page = TmiPage.objects.create(tmi_origin=birthday_page)
                photo_page = PhotoPage.objects.create(photo_origin=birthday_page)
                
                #페이지에 입력된 생일을 받아서 올해 생일이 지났는지 판별
                birthday_month = birthday_page.owner.birthday.month
                birthday_day = birthday_page.owner.birthday.day
                birthday_thisyear = datetime.strptime(str(today_year)+str(birthday_month)+str(birthday_day), "%Y%m%d").date() #올해 생일
                
                birthday = birthday_thisyear #생일은 올해 생일로 초기화한다
                date_diff = abs((today-birthday).days)
                
                if birthday_thisyear < today: #올해 생일이 이미 지났다면 내년 생일 페이지를 미리 생성해 줌
                    page_year = today_year + 1
                    birthday = datetime.strptime(str(today_year+1)+str(birthday_month)+str(birthday_day), "%Y%m%d").date() #생일을 내년 생일로 한다
                    date_diff = abs((today-birthday).days)
                    
                    if date_diff < 7:
                        tmi_page.state = "activate"
                        photo_page.state = "activate"
                        birthday_page.state = "upcoming"
                    elif date_diff == 7:
                        tmi_page.state = "activate"
                        photo_page.state = "activate"
                        birthday_page.state = "today"
                    else:
                        tmi_page.state = "deactivate"
                        photo_page.state = "deactivate"
                        birthday_page.state = "waiting"
                else:                         #올해 생일이 아직 지나지 않았다면 올해 생일 페이지가 생성됨
                    page_year = today_year
                    if date_diff < 7:
                        tmi_page.state = "activate"
                        photo_page.state = "activate"
                        birthday_page.state = "upcoming"
                    elif date_diff ==7:
                        tmi_page.state = "activate"
                        photo_page.state = "activate"
                        birthday_page.state = "today"
                    else:
                        tmi_page.state = "deactivate"
                        photo_page.state = "deactivate"
                        birthday_page.state = "waiting"
                    
                birthday_page.year = page_year
                birthday_page.save()
                
                tmi_page.year = page_year
                photo_page.year = page_year
                tmi_page.save()
                photo_page.save()
                
                #만들어진 페이지로 redirect
                return redirect(f"{birthday_page.year}/{birthday_page.uuid}")
            else :
                return redirect('/create')
        else :
            form = BirthdayPageForm(request.POST)
            context={
                'form':form,
            }
            return render(request, 'posts/create_birthday_page.html', context=context)
    else :
        return redirect("login/?next=/")
    
def detailBirthdayPage(request,year,pk):
    #도메인 년도 비교용 전역변수
    today = datetime.now().date() #현재 날짜
    today_year = today.year #현재 년도
    next_year = today_year + 1

    birthday_page = get_object_or_404(BirthdayPage, year=year, pk=pk)
    messages = birthday_page.message_set.all()
    name = birthday_page.owner.nickname
    
    if request.user == birthday_page.owner :
        is_owner = 1 #현재 접속자가 이 생일 페이지의 주인인지 알려주는 플래그
    else :
        is_owner = 0

    birthday_month = birthday_page.owner.birthday.month #생일자의 생일 월
    birthday_day = birthday_page.owner.birthday.day #생일자의 생일 일

    birthday_thisyear = datetime.strptime(str(today_year)+str(birthday_month)+str(birthday_day), "%Y%m%d").date() #올해 생일
    birthday = birthday_thisyear #생일은 올해 생일로 초기화한다
    date_diff = abs((today-birthday).days) 
        
    #생일이 자정이 지나 끝나면 비활성화
    if birthday_thisyear >= today :
        curr_page = birthday_page
        tmi_page = TmiPage.objects.get(tmi_origin=curr_page)
        photo_page = PhotoPage.objects.get(photo_origin=curr_page)
        if date_diff == 0:
            curr_page.state = 'today'
            tmi_page.state = 'activate'
            photo_page.state = 'activate'
        elif date_diff <=7:
            curr_page.state = "upcoming"
            tmi_page.state = 'activate'
            photo_page.state = 'activate'
        else:
            curr_page.state = "waiting"
            tmi_page.state = 'deactivate'
            photo_page.state = 'deactivate'
        curr_page.save()
        tmi_page.save()
        photo_page.save()
    else:
        if is_owner == 1:
            if BirthdayPage.objects.filter(owner=request.user, year=today_year).exists():    
                birthday = datetime.strptime(str(today_year+1)+str(birthday_month)+str(birthday_day), "%Y%m%d").date() #생일을 내년 생일로 한다
                date_diff = abs((today-birthday).days)
                if not BirthdayPage.objects.filter(owner=request.user, year=next_year).exists():
                    curr_page = BirthdayPage.objects.get(owner=request.user, year=today_year)
                                
                    next_page = BirthdayPage.objects.create(owner=request.user, year=next_year)
                    next_name = curr_page.owner.nickname
                    next_birth = curr_page.owner.birthday
                    next_cake = curr_page.owner.selected_cake
                                
                    next_page.owner.nickname= next_name
                    next_page.owner.birthday = next_birth
                    next_page.owner.selected_cake = next_cake
                    next_page.owner.save()
                    
                    tmi_page = TmiPage.objects.create(tmi_origin = next_page, year= next_page.year)
                    photo_page = PhotoPage.objects.create(photo_origin = next_page, year= next_page.year)
                        
                    if date_diff <=7:
                        next_page.state = "upcoming"
                        tmi_page.state = "activate"
                        photo_page.state = "activate"
                    else:
                        next_page.state = "waiting"
                        tmi_page.state = "deactivate"
                        photo_page.state = "deactivate"
                        
                    next_page.save()
                    tmi_page.save()
                    photo_page.save()
                        
                    
                    curr_page.state = "archive"
                    curr_page.save()
                    return redirect(f"/{next_page.year}/{next_page.uuid}")
                else:
                    curr_page = BirthdayPage.objects.get(owner=request.user, year=today_year)
                    curr_page.state = "archive"
                    curr_page.save()
                    
                    tmi_page = TmiPage.objects.get(tmi_origin=curr_page)
                    photo_page = PhotoPage.objects.get(photo_origin=curr_page)
                    
                    tmi_page.state = "archive"
                    photo_page.state = "archive"
                    
                    tmi_page.save()
                    photo_page.save()
            else:
                birthday = datetime.strptime(str(today_year+1)+str(birthday_month)+str(birthday_day), "%Y%m%d").date() #생일을 내년 생일로 한다
                date_diff = abs((today-birthday).days)
                curr_page = birthday_page
                if date_diff == 0:
                    curr_page.state = 'today'
                elif date_diff <=7:
                    curr_page.state = "upcoming"
                else:
                    curr_page.state = "waiting"
                    curr_page.save()
        else: #생일 페이지 주인이 아닌 다른 접속자가 접속했을 경우 archive 처리
            curr_page = birthday_page

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- meta -->
    <meta property="og:url" content="https://chookapoka.com/">
    <meta property="og:title" content="추카포카 - 생일은 추카포카에서, 우리 같이 축하해요!"/>
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://raw.githubusercontent.com/Piro17-Project-Birthday/Piro17-Project-Birthday/main/static/img/og-image.jpg"/>
    <meta property="og:description" content="친구의 생일페이지에 축하의 마음을 남겨주세요."/>
    <meta property="og:site_name" content="추카포카">
    <meta property="og:locale" content="ko">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:title" content="추카포카 - 생일은 추카포카에서, 우리 같이 축하해요!"/>
    <meta name="twitter:description" content="친구의 생일페이지에 축하의 마음을 남겨주세요."/>
    <meta name="twitter:image" content="https://raw.githubusercontent.com/Piro17-Project-Birthday/Piro17-Project-Birthday/main/static/img/og-image.jpg" />
    <meta property="site_title" content="추카포카 - 생일은 추카포카에서, 우리 같이 축하해요!"/>
    <link rel="icon" href="/static/img/page_logo/favicon.png">

    <title>추카포카</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
  </head>

  <body>
    {% if user.is_authenticated %}
          <nav>
            <div class="nav__left">
              <a href="/"><img class="nav__logo" src="{% static 'img\page_logo\logo-dark.png' %}" alt=""></a>
            </div>
            <div class="navbar_dropdown">
              <button onclick="dropdown_menu()" class="dropdown__btn">
                <img src="{% static 'img/icon/nav.svg' %}">
              </button>
              <div  id="dropdown_content">
                
                <div class="dropdown__box" style="transform: translateX(14rem); opacity: 0%;" id="dropdown_content_sidebar">
                  <button onclick="dropdown_menu_x()" class="dropdown__btn--x">
                    <img src="{% static 'img/icon/close.svg' %}">
                  </button>
                  {% if user.nickname %}
                    <a href="{% url 'posts:main_mypage'%}"><img src="{% static 'img/icon/user.svg' %}">
                      {{user.nickname}} 님</a>
                  {% else %}
                    <a href="{% url 'posts:main_mypage'%}"><img src="{% static 'img/icon/user.svg' %}">
                      {{user.username}} 님</a>
                  {% endif %}
                  <!-- 내페이지 링크 연결 -->
                  <div>
                    <img class="dropdown__wave-pattern" src="{% static 'img\wave-pattern-nav-bar.svg' %}">
                    <div id="dropdown__background">
                      <a href="{% url 'posts:main_mypage'%} " id="dropdown__mypage">마이페이지</a>
                      <a href="mailto:eastlaw80@naver.com" id="dropdown__btn--service">1:1 문의하기</a>
                      <a href="{% url 'users:log_out'%}" id="dropdown__btn--logout">로그아웃</a>
                    </div>
                  </div>
                  
                </div>
                <div style="display: none;" class="dropdown__opacity"></div>
              </div>
              
            </div>
          </nav>
        {% else %}
          <nav>
            <div class="nav__left">
              <a href="/"><img class="nav__logo" src="{% static 'img\page_logo\logo-dark.png' %}" alt=""></a>
            </div>
            <div class="navbar_dropdown">
              <button onclick="dropdown_menu()" class="dropdown__btn">
                <img src="{% static 'img/icon/nav.svg' %}">
              </button>
              <div  id="dropdown_content">
                
                
                <div class="dropdown__box" style="transform: translateX(14rem); opacity: 0%;" id="dropdown_content_sidebar">
                  <button onclick="dropdown_menu_x()" class="dropdown__btn--x">
                    <img src="{% static 'img/icon/close.svg' %}">
                  </button>
                <a href="/login/?next={{ request.path }}" class="dropdown__btn--login"><img src="{% static 'img/icon/user.svg' %}">
                  로그인 하기 ></a>
                  <img class="dropdown__wave-pattern" src="{% static 'img\wave-pattern-nav-bar.svg' %}">
                  <div id="dropdown__background">
                  <a href="mailto:eastlaw80@naver.com" id="dropdown__btn--service">1:1 문의하기</a>
                  </div>
              </div>
              <div style="display: none;" class="dropdown__opacity"></div>
            </div>
          </nav>
        {% endif %}
    <div class="wrap">
      
      <div class="screen">
        
        {% block content %}{% endblock %}
      </div>
    </div>
    <script>
      function dropdown_menu() {
        let click = document.getElementById("dropdown_content_sidebar");
        const background = document.getElementsByClassName("dropdown__opacity")[0]
        if (click.style.transform = "translateX(14rem)") {
          //click.style.display= "block";
          click.style.opacity= "100%";
          click.style.transform = "translateX(0px)";//나옴
          background.style.display="block";

        } else {
          //click.style.display= "none";
          click.style.opacity= "0%";
          click.style.transform = "translateX(14rem)";//들어감
          background.style.display="none";
        }
        
        background.onclick = function () {
          click.style.opacity= "0%";
          click.style.transform = "translateX(14rem)";
          background.style.display="none";
        }
      }


      function dropdown_menu_x() {
        let click = document.getElementById("dropdown_content_sidebar");
        const background = document.getElementsByClassName("dropdown__opacity")[0]
        if (click.style.transform = "translateX(0px)") {
          //click.style.display= "none";
          click.style.opacity= "0%";
          click.style.transform = "translateX(14rem)";
          background.style.display="none";

        } else {
          //click.style.display= "block";
          click.style.opacity= "100%";
          click.style.transform = "translateX(0px)";
          background.style.display="block";
        }
       
        background.onclick = function () {
          click.style.opacity= "0%";
          click.style.transform = "translateX(14rem)";
          background.style.display="none";
        }
      }

      function setScreenSize() {
        let vh = window.innerHeight * 0.01;
        document.documentElement.style.setProperty('--vh', `${vh}px`);
      }
      setScreenSize();
      
      window.addEventListener('resize', () => setScreenSize());
    </script>
</body>

</html>

posts/templates/posts/base_mypage.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- css 참조 안쓰고 그냥 style로 함. -->
    <link rel="icon" href="/static/img/page_logo/favicon.png">
    <title>추카포카</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base_mypage.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main_mypage.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/edit_mypage.css' %}"/>
  </head>

  <body>
    <div class="wrap">
      <div class="screen">
        <nav>
          <div class="nav__left">
            <a onclick="goBack();">
              <img src="{% static 'img\icon\chevron-left.svg' %}" alt="">
            </a>
          </div>
          <div class="nav__middle">
              <span>
                {% if curr_page == "edit" %}
                  정보 수정
                {% else %}
                  마이페이지
                {% endif %}
              </span>
          </div>
          <div class="nav__right"></div>
        </nav>
        {% block content %}{% endblock %}
      </div>
    </div>
    <script>
      function goBack() {
        window
          .history
          .back();
      }
    </script>
  </body>

</html>

posts/templates/posts/create_birthday_page.html
{% extends 'posts/base.html' %} {% block content %} {% load static %}
<script>
  $.ajaxSetup({
    headers: { "X-CSRFToken": "{{csrf_token}}" },
  });
</script>
<head>
  <link rel="stylesheet" href="{% static 'css/create_birthday_page.css' %}" />
</head>
<body>
  <div class="content">
    
    <div class="archive">
      <div class="archive__text">
        <p>
          생일을 제외한 정보는 마이페이지에서 수정할 수 있어요.
        </p>
      </div>
    </div>
    

    <form action="/create" method="POST" class="create_birthday_page__form">
      {% csrf_token %}
      <div class="create__name">
        <span class="create__name__text">이름을 알려주세요.</span>
        <span class="create__birthday__sub-text">최대 10자</span>
        <div>
          <input type="text" name="nickname" maxlength="10" required="" id="id_nickname" Placeholder="이름도, 닉네임도 좋아요. "> 
        </div>
      </div>
      <div class="create__birthday">
        <span class="create__birthday__text">생일을 알려주세요.</span>
        <span class="create__birthday__sub-text_b">수정이 불가해요</span>
        <input type="date" name="birthday" required="" id="id_birthday">
    </div>
      <div class="create__cake">
        <div class="create__cake__text">페이지를 장식할 테마를 선택해주세요.</div>
        <div>
          <ul id="id_selected_cake">
            <li>
              <img class="preview__choco" src="{% static 'img/theme-preview-choco.png' %}" alt="">
              <label for="id_selected_cake_0"><input type="radio" name="selected_cake" value="choco" required="" id="id_selected_cake_0">초코</label>
            </li>

            <li>
              <img class="preview__strawberry" src="{% static 'img/theme-preview-strawberry.png' %}" alt="">
              <label for="id_selected_cake_1"><input type="radio" name="selected_cake" value="strawberry" required="" id="id_selected_cake_1">딸기</label>
            </li>

            <li>
              <img class="preview__carrot" src="{% static 'img/theme-preview-carrot.png' %}" alt="">
              <label for="id_selected_cake_2"><input type="radio" name="selected_cake" value="carrot" required="" id="id_selected_cake_2">당근</label>
            </li>
          </ul>
        </div>
      </div>
      <input type="submit" value="제출하기" class="primary-btn" id="birthday_create_page--submit"/>
    </form>
  </div>
</body>
{% endblock content %}

posts/templates/posts/create_message.html
{% extends 'posts/base.html' %} {% block content %} {% load static %}
<script>
  $.ajaxSetup({
    headers: { "X-CSRFToken": "{{csrf_token}}" },
  });
</script>
<link rel="stylesheet" href="{% static 'css/create_message.css' %}" />
<body>
  <div class="content">
    <form
      action="{% url 'posts:create_message' birthday_page.year birthday_page.pk %}"
      method="POST"
    >
      {% csrf_token %}
      <table>
        <form action="" method="POST">
          <input
            type="hidden"
            name="csrfmiddlewaretoken"
            value="N3mQsgeKPQEhYgexGgQPRxHe4SCZI8wLwCVWM8UqPOvAAl2ggeIRaQJLN3jFLjdg"
          />
          {% csrf_token %}
          <p>
            <label for="id_nickname" class="create_message--name"
              >이름을 알려주세요.</label
            >
            <span class="create__message__sub-text">최대 10자</span>
            <input
              type="text"
              name="nickname"
              maxlength="10"
              required=""
              id="id_nickname"
              placeholder="이름도, 닉네임도 좋아요.   "
            />
          </p>
          {% csrf_token %}
          <p>
            <label for="id_message" class="create_message--send"
              >메세지를 남겨주세요.</label>
            
            <textarea
              name="message"
              cols="40"
              rows="10"
              required=""
              id="id_message"
              placeholder="따뜻한 축하의 마음을 전해주세요."
            ></textarea>
          </p>
          {% if request.user.is_authenticated%}
          <div class="check-private">
            <input type="checkbox" name="is_private" id="id_is_private" />
          <label for="id_is_private" class="create_message--private"
            >비밀 메세지</label>
          </div>
          {% endif %}
        </form>
      </table>
      {% csrf_token %}
      <input
        type="submit"
        class="create_message--submit"
        value="메시지 남기기"
      />
    </form>
  </div>
</body>
{% endblock content %} 

posts/templates/posts/main_mypage.html
{% extends 'posts/base_mypage.html' %}
{%block content %}
  {% load static%}
  <script src="https://kit.fontawesome.com/f578b19b63.js" crossorigin="anonymous"></script>
  <body>
    <div class="content">
      <div class="mypage__profile--image">
        <img src="{% static 'img\icon\user-dark.svg' %}" alt=""/>
      </div>
      <div class="mypage__profile--name">
        {% if curr_user.nickname %}
          <div>
            {{curr_user.nickname}} 님
          </div>
        {% else %}
          <div>
            {{curr_user.username}} 님
          </div>
        {% endif %}
      </div>
      <hr class="mypage__line">
      <div class="mypage__content">
        <!-- 올해 페이지가 존재하는데 waiting일 경우 -->
        <div class="mypage__content__thisyear">
          <div class="text__top">
            <span>
              내 생일 페이지
            </span>
            {% if thisyear_page %}
              {% if thisyear_page.state == "today" or thisyear_page.state == "upcoming" or thisyear_page.state == "waiting" %}
                <a href="{% url 'posts:edit_mypage' %}" class="mypage__edit_mypage">
                  정보 수정
                </a>
              {% endif %}
            {% endif %}
          </div>
          {% if thisyear_page %}
            {% if thisyear_page.state == "waiting" %}
              <form action="{% url 'posts:detail_birthday_page' thisyear_page.year thisyear_page.pk %}" method="post">
                {% csrf_token %}
                <button class="mypage__go-to-my-birthday-page waiting">
                  {{ thisyear_page.year }}년
                  {{ thisyear_page.owner.birthday.month }}월
                  {{ thisyear_page.owner.birthday.day }}일
                </button>
              </form>
              <div class="mypage__info-text">
                아직 생일 페이지가 활성화되지 않았어요!
              </div>
              <div class="mypage__info__sub-text">
                <span>생일페이지는 생일 7일전 부터 생일 당일 자정까지 활성화 돼요.</span></div>
              </div>
            <!-- 올해 페이지가 존재하는데 활성화되었을 경우 -->
            {% else %}
              {% if thisyear_page.state == "today" or thisyear_page.state == "upcoming" %}
                <form action="{% url 'posts:detail_birthday_page' thisyear_page.year thisyear_page.pk %}" method="post">
                  {% csrf_token %}
                  <button class="mypage__go-to-my-birthday-page">
                    {{ thisyear_page.year }}년
                    {{ thisyear_page.owner.birthday.month }}월
                    {{ thisyear_page.owner.birthday.day }}일
                  </button>
                </form>
              {% endif %}
            {% endif %}
          <!-- 올해 페이지가 존재하지 않는 경우 -->
          {% else %}
            <div class="mypage__info-text">
              아직 생일 페이지가 만들어지지 않았어요!
            </div>
            <div class="mypage__info__sub-text-make">
              <span>나만의 생일 페이지를 만들어볼까요?</span>
            </div>
            <div>
              <button class="mypage__go-to-make-page">
              <a href="{% url 'posts:create_birthday_page'%}">
                생일 페이지 만들기
              </a>
              </button>
            </div>
          {% endif %}
        </div>
        <div class="mypage__content__archive">
          <div class="text__top">
            <span>
              지난 생일 페이지
            </span>
          </div>
          {% if archived_pages %}
          {% for archived_page in archived_pages %}
            <form action="{% url 'posts:detail_birthday_page' archived_page.year archived_page.pk %}" method="post">
              {% csrf_token %}
              <button class="mypage__go-to-past-birthday-page">
                {{ archived_page.year }}년
                {{ archived_page.owner.birthday.month }}월
                {{ archived_page.owner.birthday.day }}일
              </button>
            </form>
          {% endfor %}
        {% else %}
          <div class="mypage__info-text">
            아직 저장된 지난 생일 페이지가 없어요!
          </div>
        {% endif %}

        </div>

      </div>
    </div>
  </body>
{% endblock %}

posts/templates/posts/write.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    <form action="{% url 'posts:write' birthdayPage.owner.id %}" method="POST">
      {% csrf_token %}
      <table>
        {{form.as_p}}
      </table>
      <input type="submit" value="메시지 남기기" />
  </form>
</body>

</html>